# Generated by Django 6.1.1 on 2026-09-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliotheque', '0009_remove_emprunteur_livres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('livres', models.ManyToManyField(through='bibliotheque.Emprunt', to='bibliotheque.livre')),
            ],
        ),
    ]
