# Generated by Django 6.1.1 on 2026-09-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='date_publication',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livre',
            name='langue',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('KO', 'Korean')], default='FR', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livre',
            name='resume',
            field=models.TextField(blank=True),
        ),
    ]
