# Generated by Django 5.2.17 on 2026-09-17 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField()),
                ('date_retour_prevue', models.DateField()),
                ('date_retour_effective', models.DateField(blank=True, null=True)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.livre')),
            ],
        ),
        migrations.CreateModel(
            name='Emprunteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('livres', models.ManyToManyField(related_name='emprunteurs', through='bibliotheque.Emprunt', to='bibliotheque.livre')),
            ],
        ),
        migrations.AddField(
            model_name='emprunt',
            name='emprunteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.emprunteur'),
        ),
    ]
