# Generated by Django 5.2.17 on 2026-09-17 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0002_emprunt_emprunteur_emprunt_emprunteur'),
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='emprunteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membres.emprunteur'),
        ),
        migrations.DeleteModel(
            name='Emprunteur',
        ),
    ]
