# Generated by Django 6.1.1 on 2026-09-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0002_livre_date_publication_livre_langue_livre_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='id',
        ),
        migrations.AlterField(
            model_name='livre',
            name='isbn',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
