# Generated by Django 6.1.1 on 2026-09-17 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0003_remove_livre_id_alter_livre_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibliotheque.auteur'),
        ),
    ]
