# Generated by Django 6.1.1 on 2026-09-17 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0006_emprunt_emprunteur_emprunt_emprunteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheAuteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biographie', models.TextField()),
                ('site_web', models.CharField(max_length=100)),
                ('auteur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.auteur')),
            ],
        ),
    ]
