# Generated by Django 6.1.1 on 2026-09-17 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0007_ficheauteur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name_plural': 'genres'},
        ),
        migrations.AlterModelOptions(
            name='livre',
            options={'ordering': ['titre']},
        ),
    ]
