# Generated by Django 6.1.1 on 2026-09-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0008_alter_genre_options_alter_livre_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunteur',
            name='livres',
        ),
    ]
