# Generated by Django 6.1.1 on 2026-09-17 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0009_remove_emprunteur_livres'),
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='emprunteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membres.emprunteur'),
        ),
        migrations.DeleteModel(
            name='Emprunteur',
        ),
    ]
